# Generated by Django 4.1 on 2022-09-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='shopproducts',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='content',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='photo',
            field=models.ImageField(upload_to='img', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
    ]
